### ISSUE TITLE
Database Modifications

### ISSUE THREAD

**Issue by Shwam** [KellenWatt/hundis#6]
Users:
- remove "pass" and "salt" fields
- add "admin" bool field

Clean up duplicate "tournaments_id"/"tournament_id" in various tables
Clean up duplicate "problems_id"/"problem_id"

**Comment by Shwam** [comment]
Resolved by a1f148a

**Comment by skgrush** [comment]
@Shwam forgot to add the "admin" bool field!

**Comment by skgrush** [comment]
Resolved by b7ff606

**Comment by Shwam** [comment]
Forgot to remove the pass and salt fields!

Issues are hard.
